config/routes.rb
Rails.application.routes.draw do
  root 'playgrounds#index'
  get 'relationships/create'
  get 'relationships/destroy'
  delete '/logout',to: 'sessions#destroy'
  resources :sessions, only: [:new, :create, :destroy]
  resources :playgrounds
  resources :posts
  resources :myakachans
  resources :conversations do
    resources :messages
  end
  resources :users
  resources :users do
    member do
      get :following, :followers
    end
  end #only: [ :new, :create, :show, :edit]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :relationships, only: [:create, :destroy]

end

app/models/playground.rb
class Playground < ApplicationRecord
  mount_uploader :image, ImageUploader
    validates :name,  presence: true, length: { maximum: 30 }
    validates :address,  presence: true, length: { maximum: 100 }
    validates :image, presence: true, allow_nil: true
    validates :opening_at, presence: true
    validates :closing_at, presence: true
    belongs_to :user, optional: true
    has_many :posts, dependent: :destroy

  end

app/controllers/playgrounds_controller.rb
class PlaygroundsController < ApplicationController
  before_action :set_playground,only: [:show, :edit, :update, :destroy]

  def index

    @q = Playground.ransack(params[:q])
    @playgrounds = @q.result(distinct: true).page(params[:page]).per(6)
  end

  def show
    # binding.pry
    @post = Post.new
    @posts = @playground.posts
  end

  def new
    @playground = Playground.new
  end

  def create
    @playground= current_user.playgrounds.build(playground_params)
    if @playground.save
      flash[:notice] = "Has been playground register."
      redirect_to playground_path(@playground.id)
    else
      flash.now[:notice] = "fails to playground register"
      render :new
    end
  end

  def edit
  end

  def update
    if @playground.update(playground_params)
      redirect_to playground_path(@playground.id), notice: 'Has been edit playground！'
    else
      render :edit
    end
  end

  def destroy
    @playground.destroy
    redirect_to playgrounds_path,notice: 'Playground was successfully destroyed.'
  end

  private

  def set_playground
    @playground = Playground.find(params[:id])
  end

  def playground_params
    params.require(:playground).permit(:name, :address, :opening_at, :closing_at, :price, :breadth, :other, :image, :image_cache, :name_cont)
  end

end

app/helpers/playgrounds_helper.rb
module PlaygroundsHelper
end

app/views/playgrounds/_form.html.erb
<div class="container">
  <div class="row">
<%= form_with(model: playground, local: true) do |f| %>
  <% if playground.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% playground.errors.full_messages.each do |message| %>
        <h2><%= message %></h2>
      <% end %>
      </ul>å
    </div>
  <% end %>

  <div class="field">
    <%= f.label :playground_name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :business_hours %>
    <%= f.time_select :opening_at  %>　〜
    <%= f.time_select :closing_at  %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :breadth %>
    <%= f.text_field :breadth  %>
  </div>

  <div class="field">
    <%= f.label :other %>
    <%= f.text_field :other  %>
  </div>

  <div class="field">
    <%= f.label :image %><br />
    <%= image_tag(@playground.image.url, size: '200x200')  if @playground.image && @playground.image.url %>
    <%= f.file_field :image %>
    <%= f.hidden_field :image_cache %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>
  </div>
</div>

app/views/playgrounds/edit.html.erb
<div class="container">
  <div class="row">
  <h4>Editing playground</h4>
  <%= render 'form', playground: @playground %>
  <%= link_to 'Show', @playground %> |
  <%= link_to 'Back', playgrounds_path %>
  </div>
</div>

app/views/playgrounds/index.html.erb
<h2>playground Lists</h2>

<%= search_form_for @q do |f| %>
    <h3><%= f.label :playground, "Search by address" %>
    <%= f.search_field :address_cont %>
    <%= f.submit t('search') %>
    </h3>
<% end %>

<% if log_in? %>
<h4><%= link_to t('playground register'), new_playground_path %></h4>
<% end %>

<div class="main">
<% @playgrounds.each do |playground| %>
  <section class="card">
    <%= image_tag playground.image.url,class:"card-img"%>
      <div class="card-content">
      <h1 class="card-title"><%= playground.name %></h1>
      <p class="card-text"><%= playground.address %></p>
    <div class="card-link">
        <%= link_to t('Details'), playground_path(playground) %>
        <% if log_in? && playground.user.id == current_user.id %>
        <%= link_to t('Edit'), edit_playground_path(playground) %>
        <%= link_to 'Delete', playground_path(playground), method: :delete, data: { confirm: 'Are you sure delete?' }  %>
        <% end %>
    </div>
  </section>
<% end %>
</div>

app/views/playgrounds/new.html.erb
<div class="container">
  <div class="row">
  <h4>playground new register</h4>
  <%= render 'form', playground: @playground %>
  <%= link_to 'Return', playgrounds_path %>
  </div>
</div>

app/views/playgrounds/show.html.erb
<div class="container">
  <div class="row">

  <h2>Playground information</h2>

  <div class="list">
  <div class="card-img"><%= image_tag @playground.image.url, width: "500px" %></div>
  </div>

  <p>
  <strong><%= t('playground_name') %> :</strong>
  <%= @playground.name %>
  </p>

  <p>
  <strong><%= t('address') %> :</strong>
  <%= @playground.address %>
  </p>

  <p>
  <strong><%= t('business hours') %> :</strong>
  <%= @playground.opening_at.hour%> :
  <%= @playground.opening_at.min %> ~
  <%= @playground.closing_at.hour%> :
  <%= @playground.closing_at.min%>
  </p>

  <p>
    <strong><%= t('price') %> :</strong>
    <%= @playground.price %>
  </p>

  <p>
    <strong><%= t('breadth') %> :</strong>
    <%= @playground.breadth %>
  </p>

  <p>
    <strong><%= t('other') %> :</strong>
    <%= @playground.other %>
  </p>

  <p>
    <%= link_to 'Playground User' ,user_path(@playground.user) %>
      <% if @playground.user.image? %>
        <%= image_tag  @playground.user.image.url,size: '100x100' %>
      <% else %>
        <%= image_tag "/assets/default.jpg" %>
      <% end %>
      <% if log_in? && @playground.user_id == current_user.id %>
        <%= link_to 'Edit Playground information', edit_playground_path(@playground) %>
      <% end %>
  </p>


  <table>
  <h2>Review List</h2>
    <thead>
      <tr>
        <th><%= t('title') %></th>
        <th><%= t('content') %> </th>
        <th><%= t('image') %> </th>
        <th><%= t('poster') %> </th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td><%= post.title %></td>
          <td><%= post.content %></td>
          <% if post.image.url present? %>
          <td><%= image_tag post.image.url,size: '200x200' %></td>
          <% end %>
          <td><%= link_to t('poster'), user_path(post.user_id) %></td>
          <td><%= link_to t('Details'), post %></td>
          <% if log_in? && post.user_id == current_user.id %>
          <td><%= link_to t('Edit'), edit_post_path(post) %></td>
          <td><%= link_to t('Delete'), post, method: :delete, data: { confirm: 'Are you sure delete?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <% if log_in? %>
  <h3>To post Review</h3>
  <%= form_with model: @post, local: true  do |f| %>
  <%= f.hidden_field :playground_id, value: @playground.id %>
  <%= f.hidden_field :user_id, value: @current_user.id %>
    <% if @post.errors.any? %>
      <div id="error_explanation">
      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <h2><%= message %></h2>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :content %>
    <%= f.text_field :content %>
  </div>

  <div class="field">
    <%= f.label :画像 %>
    <%= image_tag(@post.image.url) if @post.image && @post.image.url %>
    <%= f.file_field :image %>
    <%= f.hidden_field :image_cache %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

    <% end %>
  <% end %>



<%= link_to 'Return to Playground lists', playgrounds_path, class:"btn btn-primary" %>
      </div>
    </div>