config/routes.rb
Rails.application.routes.draw do
  root 'playgrounds#index'
  get 'relationships/create'
  get 'relationships/destroy'
  delete '/logout',to: 'sessions#destroy'
  resources :sessions, only: [:new, :create, :destroy]
  resources :playgrounds
  resources :posts
  resources :myakachans
  resources :conversations do
    resources :messages
  end
  resources :users
  resources :users do
    member do
      get :following, :followers
    end
  end #only: [ :new, :create, :show, :edit]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :relationships, only: [:create, :destroy]

end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image, ImageUploader
  before_validation { email.downcase! }
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 50 },
  format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },uniqueness: true
  validates :password, presence: true, length: { minimum: 4 } ,allow_nil: true

  has_secure_password
  has_many :playgrounds, dependent: :destroy
  has_many :posts
  has_many :myakachans, dependent: :destroy
  has_many :active_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :passive_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  def follow!(other_user)
    active_relationships.create!(followed_id: other_user.id)
  end
  #フォローしているかどうかを確認する
  def following?(other_user)
    active_relationships.find_by(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "New User register login!"
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      flash[:notice] = "Register Failed!"
      render :new
    end
  end

  def show
    @myakachan = Myakachan.new
    @myakachans = @user.myakachans
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'I edited my profile！'
    else
      render :edit
    end
  end

  def following
    @user  = User.find(params[:id])
    @users = @user.following
    render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

  private
 def user_params
    params.require(:user).permit(
      :password_confirmation,
      :password,:name,
      :email,
      :admin_or_not,
      :image,
      :image_cache,
      :profile )
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_form.html.erb
<div id="follow_form_<%= user.id %>">
  <% unless current_user.following?(user) %>
    <%= form_with(model: current_user.active_relationships.build(followed_id: user.id)) do |f| %>
      <%= f.hidden_field :followed_id %>
      <%= f.submit "Follow" %>
    <% end %>
  <% else %>
  
    <%= form_with(model: current_user.active_relationships.find_by(followed_id: user.id), method: :delete ) do |f| %>
      <%= f.submit "Unfollow" %>
    <% end %>
  <% end %>
</div>

app/views/users/_form.html.erb
<div class="wrapper">
  <h2 calss="usericon">Sign up</h2>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_with(model: @user, local: true) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div><br>
  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div><br>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div><br>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div><br>
  <div class="field">
    <div class="form-group">
      <%= f.label :image %>
      <%= f.file_field :image %>
      <%= f.hidden_field :image_cache %>
      <%= image_tag @user.image_url if @user.image? %>
    </div>
  </div>
    <br>
  <div class="field">
    <%= f.submit "Create my account" %>
  </div>
  <% end %>
</div>

app/views/users/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followings.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
  <h1>Profile edit</h1>
  <%= render 'form', user: @user %>
  <%= link_to 'Back', @user %>
  </div>
</div>

app/views/users/new.html.erb
<div class="wrapper">
  <h2>Sign up</h2>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_with(model: @user, local: true) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div><br>
  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div><br>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div><br>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div><br>
  <div class="field">
    <div class="form-group">
      <%= f.label :image %>
      <%= f.file_field :image %>
      <%= f.hidden_field :image_cache %>
      <%= image_tag @user.image_url if @user.image? %>
    </div>
  </div>
    <br>
  <div class="field">
    <%= f.submit "Create my account" %>
  </div>
  <% end %>
</div>

app/views/users/show.html.erb
<td class="container">
  <div>
  <% if log_in? && @user.id == current_user.id %>
      <h2>My Page</h2>
  <% else %>
      <h3>Profile</h3>
  <% end%>
  </div>

<table>
  <tbody>
    <tr>
  <% if @user.image? %>
      <td><%= image_tag @user.image.url, size: '200x200' %></td>
  <% else %>
      <td><%= image_tag "/assets/default.jpg", size: '100x100' %></td>
  <% end %>
    </tr>
      <tr><%= @user.name %></tr>
      <tr>コメント: <%= @user.profile %></tr>
  <% if log_in? && @user.id == current_user.id %>
      <td><%= link_to 'Edit profile', edit_user_path(@user) %></td>
  <% end%>
  <% if log_in? && @user.id != current_user.id %>
      <td><%= link_to 'To send message', conversations_path(sender_id: current_user.id, recipient_id: @user.id), method: :post %></<td>
      <td><%= render 'follow_form', user: @user %></td>
  <% end%>
      <td><%= link_to "following", following_user_path(@user) %></td>
      <td><%=  @user.following.count %></td>
      <td><%= link_to "followers", followers_user_path(@user) %></td>
      <td><%=  @user.followers.count %></td>
</tbody>
</table>

  <h2>mybaby</h2>
  <table>
      <thead>
        <tr>
          <th colspan="3"></th>
        </tr>
      </thead>
    <tbody>
      <% @myakachans.each do |myakachan| %>
        <tr>
          <td><%= image_tag myakachan.image.url, size: '200x200' %></td>
          <td><%= myakachan.name %></td>
          <td><%= link_to 'Details', myakachan %></td>
        <% if log_in? && myakachan.user_id == current_user.id %>
          <td><%= link_to 'Edit', edit_myakachan_path(myakachan) %></td>
          <td><%= link_to 'Delete', myakachan_path(myakachan.id), method: :delete, data: { confirm: 'Are you sure delete?' } %></td>
        <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <% if log_in? && @user.id == current_user.id %>
    <h3>To register my baby</h3>
    <%= form_with model: @myakachan, local: true  do |f| %>
    <%= f.hidden_field :user_id, value: @user.id %>

    <% if @myakachan.errors.any? %>
      <div id="error_explanation">
        <ul>
        <% @myakachan.errors.full_messages.each do |message| %>
          <h2><%= message %></h2>
        <% end %>
        </ul>
      </div>
    <% end %>

  <div class="">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>



  <div class="field">
    <%= f.label :age %>
    <%= f.number_field :age %>
  </div>

  <div class="field">
    <%= f.label :gender %>
    <%= f.radio_button :gender, :male %>boy
    <%= f.radio_button :gender, :female %>girl
  </div>

  <div class="field">
    <%= f.label :image %>（必須）<br />
    <%= image_tag(@myakachan.image.url) if @myakachan.image && @myakachan.image.url %>
    <%= f.file_field :image %>
    <%#= input type="file",class="sell-upload-drop-file",multiple="multiple",name="image[]",style="display: none"%>
    <%= f.hidden_field :image_cache %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

    <% end %>
  <% end %>

  <div class="actions">
    <% if log_in? && @user.id == current_user.id %>
      <%= link_to "Playground create screen", new_playground_path, class:"btn btn-primary" %>
    <% end %>
  <%= link_to 'Return to playground',  playgrounds_path, class:"btn btn-primary" %>
  </div>

app/views/users/show_follow.html.erb
<% @user.following.each do |user| %>
  <td><%= user.name %> </td>
    <% if user.image? %>
  <td><%= link_to image_tag(user.image.url, size: '100x100'), user_path(user)  %> </td>
    <% end%>
<% end %>
  <br><%= link_to 'Return', @user %>

app/views/users/show_follower.html.erb
<% @user.followers.each do |user| %>
  <td><%= user.name %> </td>
    <% if user.image? %>
  <td><%= link_to image_tag(user.image.url, size: '100x100'), user_path(user)  %> </td>
    <% end%>
<% end %>
  <br><%= link_to 'Return', @user %>