config/routes.rb
Rails.application.routes.draw do
  root 'playgrounds#index'
  get 'relationships/create'
  get 'relationships/destroy'
  delete '/logout',to: 'sessions#destroy'
  resources :sessions, only: [:new, :create, :destroy]
  resources :playgrounds
  resources :posts
  resources :myakachans
  resources :conversations do
    resources :messages
  end
  resources :users
  resources :users do
    member do
      get :following, :followers
    end
  end #only: [ :new, :create, :show, :edit]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :relationships, only: [:create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
    belongs_to :sender, foreign_key: :sender_id, class_name: 'User'
    belongs_to :recipient, foreign_key: :recipient_id, class_name: 'User'
    has_many :messages, dependent: :destroy
    validates_uniqueness_of :sender_id, scope: :recipient_id
    scope :between, -> (sender_id,recipient_id) do
      where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND  conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
    end
    def target_user(current_user)
      if sender_id == current_user.id
        User.find(recipient_id)
      elsif recipient_id == current_user.id
        User.find(sender_id)
      end
    end
  end

app/models/message.rb
class Message < ApplicationRecord
  validates_presence_of :body, :conversation_id, :user_id
  
  belongs_to :conversation
  belongs_to :user

  def message_time
    created_at.strftime("%m/%d/%y at %l:%M %p")
  end
end

app/models/myakachan.rb
class Myakachan < ApplicationRecord
  mount_uploader :image, ImageUploader
    validates :name,  presence: true, length: { maximum: 30 }
    validates :age,  presence: true, length: { maximum: 2 },
    numericality: {
      greater_than_or_equal_to: 0,
      less_than: 30
    }
    validates :gender,  presence: true, length: { maximum: 10 }
    validates :image, presence: true, allow_nil: true
    belongs_to :user, optional: true
    enum gender: { male: 1, female: 2 }

  end

app/models/playground.rb
class Playground < ApplicationRecord
  mount_uploader :image, ImageUploader
    validates :name,  presence: true, length: { maximum: 30 }
    validates :address,  presence: true, length: { maximum: 100 }
    validates :image, presence: true, allow_nil: true
    validates :opening_at, presence: true
    validates :closing_at, presence: true
    belongs_to :user, optional: true
    has_many :posts, dependent: :destroy

  end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates :title,  presence: true, length: { maximum: 30 }
  validates :content,  presence: true, length: { maximum: 255 }

  belongs_to :playground, optional: true
  belongs_to :user, optional: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :followed, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image, ImageUploader
  before_validation { email.downcase! }
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 50 },
  format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },uniqueness: true
  validates :password, presence: true, length: { minimum: 4 } ,allow_nil: true

  has_secure_password
  has_many :playgrounds, dependent: :destroy
  has_many :posts
  has_many :myakachans, dependent: :destroy
  has_many :active_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :passive_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  def follow!(other_user)
    active_relationships.create!(followed_id: other_user.id)
  end
  #フォローしているかどうかを確認する
  def following?(other_user)
    active_relationships.find_by(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action do
    @conversation = Conversation.find(params[:conversation_id])
  end
def index
    @messages = @conversation.messages
    if @messages.length > 10
      @over_ten = true
      @messages = Message.where(id: @messages[-10..-1].pluck(:id))
    end
    if params[:m]
      @over_ten = false
      @messages = @conversation.messages
    end
    if @messages.last
      @messages.where.not(user_id: current_user.id).update_all(read: true)
    end
    @messages = @messages.order(:created_at)
    @message = @conversation.messages.build
  end

  def create
    @message = @conversation.messages.build(message_params)
    if @message.save
      redirect_to conversation_messages_path(@conversation)
    else
      render 'index'
    end
  end

  private

  def message_params
    params.require(:message).permit(:body, :user_id)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post,only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def show
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "Review post successfully!"
      redirect_to playground_path(@post.playground_id)
    else
      flash[:notice] = "Review Failed!"
      @playground =  Playground.find(@post.playground_id)
      @posts = @playground.posts
      render template: 'playgrounds/show'
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post.id), notice: 'Edited the review！'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to playground_path(@post.playground_id),notice: 'Post was successfully destroyed.'
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content,:image, :image_cache, :playground_id, :user_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "New User register login!"
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      flash[:notice] = "Register Failed!"
      render :new
    end
  end

  def show
    @myakachan = Myakachan.new
    @myakachans = @user.myakachans
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'I edited my profile！'
    else
      render :edit
    end
  end

  def following
    @user  = User.find(params[:id])
    @users = @user.following
    render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

  private
 def user_params
    params.require(:user).permit(
      :password_confirmation,
      :password,:name,
      :email,
      :admin_or_not,
      :image,
      :image_cache,
      :profile )
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/myakachans_helper.rb
module MyakachansHelper
end

app/helpers/playgrounds_helper.rb
module PlaygroundsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Playground for Baby！</title>
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <div id="container">
    <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

  <header>

    <div class="title"><%= link_to 'Playground for Baby!', playgrounds_path  %></div>
    <aside id="mainimg"><%= image_tag "/assets/mainimg.jpg" %></aside>
    <div>
      <p><img src="/assets/footer logo.jpg" class="footerlogo"></p>
      </div>
      <div>
        <p><img src="/assets/footer.jpg" class="footer1logo"></p>
        </div>
  </header>
  

    <div id="contents">
      <nav id="menubar">
        <ul>
          <li><%= link_to 'Playground List', playgrounds_path  %></li>
      <% if current_user %>
        <% if current_user.admin? %>
          <li><%= link_to 'User List', admin_users_path(current_user.id) %></li>
        <% end %>
          <li><%= link_to 'Logout', logout_path, method: :delete,　class: 'nav-link'  %></>
          <li><%= link_to 'My page', user_path(current_user.id) %></li>
      <% else %>
          <li><%= link_to t('Sigin up'), new_user_path %></li>
          <li><%= link_to t('Login'), new_session_path %></li>
        </ul>
      <% end %>
      </nav>
    <%= yield %>
    </div>

    <footer>

<div class="footer">
  <div class="footerleft"><img src="/assets/name.png"></div>
    <div class="footerright">  <small class="pr">Copyright© NWENI All Rights Reserved.</small>
      <span class="pr"> Follow us Twitter Facebook Youtube Instagram</span>
      <img src="/assets/footer icon.jpg"class="icon"></div>
</div>
        </footer>
  </div>
<body>